[tool.poetry]
name = "operations analysis"
version = "0.1.0"
description = ""
authors = ["PC1HA <ilia.popov.2015@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
